### ISSUE TITLE
ERROR: Failed to resolve: AnchorSheetBehavior

### ISSUE THREAD

**Issue by unshami** [skimarxall/AnchorSheetBehavior#10]
hi 
    i have been using this lib for last more than a year. But recently, I am getting this error very frequently while gradle sync. Please help me with this.

Thanks
![AnchorSheet](https://user-images.githubusercontent.com/73054161/137575635-b0017f96-4c7a-4306-9c3c-b4291c457565.png)

**Comment by marcelpinto** [comment]
I changed my github user. That causes jitpack to not find the dependency.

Switch to
`implementation 'com.github.marcelpinto:AnchorSheetBehavior:master-SNAPSHOT`

Also, consider switching to other libraries. Nowadays there are better solutions. The Material components library should have a similar component.
