### ISSUE TITLE
Set Closest state of the bottom sheet

### ISSUE THREAD

**Issue by hardikamal** [skimarxall/AnchorSheetBehavior#3]
Hi @skimarxall ,

When sliding from anchor to top and reaching almost close to top and stopping the drag, sheet comes back to the anchor position instead of top position.

Also how do i implement top to anchor and anchor to bottom sliding while closing the bottom sheet.

Thanks

**Comment by marcelpinto** [comment]
Hi sorry for not answering before.

When releasing the drag the behavior tries to find the nearest state. I agree that it might be quite sensible and could be improved, but this behavior mimics the official BottomSheetBehavior.

If you try carefully you can probably reproduce it.
