### ISSUE TITLE
ViewPager with scrollable tabs inside anchor panel doesnt scroll

### ISSUE THREAD

**Issue by laurentiugh** [skimarxall/AnchorSheetBehavior#4]
Hi guys,

I have a viewpager inside with tabs and fragments that contains nestedscrollview or recyclerview.
The problem is only the starting tab of the pager is scrollable, the rest doesnt scroll because of the AnchorSheetBehavior. I am trying to solve this but i also wanted to report the issue maybe you guys find a better solution.

[anchor.txt](https://github.com/skimarxall/AnchorSheetBehavior/files/1845219/anchor.txt)

**Comment by marcelpinto** [comment]
Hi,

Try to Wrap the linear layout with a nested scroll view and make that nested scroll view have the Anchor behavior. 

Have not tried but that might solve the problem. If you look at the source code, the Behavior accepts nested scrolls but probably they have to be direct children.

Also, a thing I did in the past if this is your main activity I would make the linear layout o be a FrameLayout and then add a Fragment with the Linear layout, the Tab and ViewPager,

**Comment by laurentiugh** [comment]
the problem is that mViewRef and mNestedScrollingChildRef members are set in onLayoutChild which gets called only for the first fragment or the viewpager and in findscrollableview we find the first scrollable view anyway :)

**Comment by marcelpinto** [comment]
I am not sure if I can help on that, most of the behavior is from the BottomSheetBehavior, there is a new version release now, I will update the code. But I am afraid I can't help with your issue
