### ISSUE TITLE
setAnchorOffset is not there

### ISSUE THREAD

**Issue by insacc** [skimarxall/AnchorSheetBehavior#5]
There is no way to set the anchor point anymore?

**Comment by marcelpinto** [comment]
I just realized also, I might have killed the method when porting it into a library. I'll fix it. Thanks

**Comment by insacc** [comment]
Thanks 🙌

**Comment by ypresto** [comment]
I want num of pixels instead of float threshold for offset argument :)

**Comment by marcelpinto** [comment]
I just port them back from previous commits, sorry for the delay
